apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd #pods must have the labels the selector is looking for
    spec:
      containers:
        - image: httpd
          name: httpd
          ports:
            - containerPort: 80