apiVersion: batch/v1
kind: Job
metadata:
  name: aws-s3-backup-once
spec:
  template:
    spec:
      containers:
        - name: aws-s3-backup-once
          image: aws-cli
          command: ["aws", "s3", "cp", "./", "s3://backups/"]
          restartPolicy: Never
      backoffLimit: 4